services:
  orcaslicer:
    build: .
    platform: linux/arm64
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./orca-config:/config/.config/OrcaSlicer
    cap_add:
      - SYS_NICE