name: Build Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'OrcaSlicer Release Tag to build'
        required: false
        type: string

jobs:
  build-orcaslicer-artifact:
    runs-on: ubuntu-24.04-arm
    outputs:
      artifact_name: OrcaSlicer_Linux_arm64
      artifact_path: ./build/package
    steps:
      - name: Clone repository
        run: git clone https://github.com/softfever/orcaslicer.git .

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.28"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf build-essential cmake curl eglexternalplatform-dev \
          extra-cmake-modules file git libcairo2-dev libcurl4-openssl-dev libdbus-1-dev libglew-dev libglu1-mesa-dev \
          libgstreamer1.0-dev libgstreamerd-3-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev \
          libgtk-3-dev libmspack-dev libsecret-1-dev libsoup2.4-dev libssl-dev libudev-dev libwayland-dev \
          libwebkit2gtk-4.1-dev libxkbcommon-dev locales locales-all m4 pkgconf sudo wayland-protocols wget libfuse2t64

      - name: Install dependencies from build_linux.sh
        shell: bash
        run: sudo ./build_linux.sh -ur

      - name: Fix permissions
        shell: bash
        run: sudo chown $USER -R ./

      - name: Build dependencies
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/deps/build
          mkdir -p ${{ github.workspace }}/deps/build/destdir
          ./build_linux.sh -dr

      - name: Build slicer
        shell: bash
        env:
          CMAKE_PREFIX_PATH: ${{ github.workspace }}/deps/build/destdir/usr/local
        run: ./build_linux.sh -sr

      - name: Upload artifacts Ubuntu
        uses: actions/upload-artifact@v4
        with:
          name: OrcaSlicer_Linux_arm64
          path: ./build/package

  build-and-push:
    needs: build-orcaslicer-artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get OrcaSlicer release version
        id: get_version
        run: |
          if [ -n "${{ github.event.inputs.release_tag }}" ]; then
            echo "RELEASE_VERSION=${{ github.event.inputs.release_tag }}" >> $GITHUB_OUTPUT
          else
            LATEST_RELEASE=$(wget -q -O- "https://api.github.com/repos/SoftFever/OrcaSlicer/releases/latest" | grep -oP '"tag_name": "\K(.*?)",$' | head -n 1 | sed 's/",$//')
            echo "RELEASE_VERSION=$LATEST_RELEASE" >> $GITHUB_OUTPUT
          fi

      - name: Download OrcaSlicer artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-orcaslicer-artifact.outputs.artifact_name }}
          path: ./downloaded_artifact

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if release image already exists
        id: check_image
        run: |
          if docker manifest inspect matszwe02/orcaslicer-arm:${{ steps.get_version.outputs.RELEASE_VERSION }} >/dev/null 2>&1; then
            echo "${{ steps.get_version.outputs.RELEASE_VERSION }} already built"
            echo "SKIP_BUILD=true" >> $GITHUB_OUTPUT
          else
            echo "SKIP_BUILD=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Build and push Docker image (release)
        if: steps.check_image.outputs.SKIP_BUILD == 'false'
        run: |
          cp -r ./downloaded_artifact/* .
          docker buildx build --platform linux/arm64 \
            --build-arg VERSION=${{ steps.get_version.outputs.RELEASE_VERSION }} \
            -t matszwe02/orcaslicer-arm:${{ steps.get_version.outputs.RELEASE_VERSION }} \
            --push .