name: Build Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Monitor resources in real time
        run: |
          nohup bash -c '
            echo "Timestamp,CPU(%),Memory(MB),Disk(%)"
            while true; do
              ts=$(date "+%Y-%m-%d %H:%M:%S")
              cpu=$(top -b -n1 | grep "Cpu(s)" | awk "{print \$2+\$4}")
              mem=$(free -m | awk "/Mem:/ {print \$3}")
              disk=$(df / | tail -1 | awk "{print \$5}")
              echo "$ts,$cpu,$mem,$disk"
              sleep 5
            done
          ' > /dev/stdout &

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/arm64 \
            --build-arg VERSION=latest \
            --build-arg QEMU_CPU_CORES=2 \
            -t matszwe02/orcaslicer-arm:latest \
            --push .